[[publication]]
title = "Learning Neural Network Controllers with Certified Robust Performance via Adversarial Training"
authors = "<strong>Neelay Junnarkar</strong>, Yasin Sonmez, Murat Arcak"
date = "2026"
doi = "https://neelayjunnarkar.com/files/local_robust_dissipativity.pdf"
pdf = "https://neelayjunnarkar.com/files/local_robust_dissipativity.pdf"
code = "https://github.com/neelayjunnarkar/local-robust-dissipativity"

[[publication]]
title = "Polynomial Constraints for Robustness Analysis of Nonlinear Systems"
authors = "<strong>Neelay Junnarkar</strong>, Peter Seiler, Murat Arcak"
date = "2026"
doi = "https://neelayjunnarkar.com/files/polynomial_constraints.pdf"
pdf = "https://neelayjunnarkar.com/files/polynomial_constraints.pdf"
code = "https://github.com/neelayjunnarkar/polynomial-constraints"

[[publication]]
title = "Stability Margins of Neural Network Controllers"
authors = "<strong>Neelay Junnarkar</strong>, Murat Arcak, Peter Seiler"
date = "2025"
doi = "https://doi.org/10.23919/ACC63710.2025.11107746"
pdf = "https://arxiv.org/pdf/2409.09184.pdf"
code = "https://github.com/neelayjunnarkar/nn-stability-margins"

[[publication]]
title = "Exploiting Symmetry in Dynamics for Model-Based Reinforcement Learning with Asymmetric Rewards"
authors = "Yasin Sonmez, <strong>Neelay Junnarkar</strong>, Murat Arcak"
date = "2024"
doi = "https://doi.org/10.1109/LCSYS.2024.3409560"
pdf = "https://arxiv.org/pdf/2403.19024.pdf"
code = "https://github.com/YasinSonmez/symmetry-cs285"
